# render.yaml
services:
  - type: web
    name: campus-eco-track
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn campusecotrack.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: campusecotrack.settings
      - key: PYTHON_VERSION
        value: 3.10
